server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
app.acquiring-bank-url=http://localhost:8080/

logging.level.com.checkout.payment.gateway.client.AcquiringBankFeignClient=TRACE
spring.cloud.openfeign.client.config.default.logger-level=FULL
spring.jackson.deserialization.fail-on-missing-creator-properties=true
